ALTER TABLE deelnemer DROP CONSTRAINT FK_DEELNEMER_VERENIGING;
ALTER TABLE hok DROP CONSTRAINT FK_HOK_AANTAL;
ALTER TABLE hok DROP CONSTRAINT FK_HOK_INSCHRIJVING_LIJN;
ALTER TABLE inschrijving_header DROP CONSTRAINT FK_INSCHRIJVING_HEADER_DEELNEMER;
ALTER TABLE inschrijving_header DROP CONSTRAINT FK_INSCHRIJVING_HEADER_EVENT;
ALTER TABLE inschrijving_lijn DROP CONSTRAINT FK_INSCHRIJVING_LIJN_AANTAL;
ALTER TABLE inschrijving_lijn DROP CONSTRAINT FK_INSCHRIJVING_LIJN_INSCHRIJVING_HEADER;
ALTER TABLE inschrijving_lijn DROP CONSTRAINT FK_INSCHRIJVING_LIJN_KLEUR;
ALTER TABLE inschrijving_lijn DROP CONSTRAINT FK_INSCHRIJVING_LIJN_RAS;
ALTER TABLE ras DROP CONSTRAINT FK_RAS_SOORT;
ALTER TABLE ras_kleur DROP CONSTRAINT FK_RAS_KLEUR_KLEUR;
ALTER TABLE ras_kleur DROP CONSTRAINT FK_RAS_KLEUR_RAS;

ALTER TABLE aantal DROP CONSTRAINT PK_aantal;
ALTER TABLE deelnemer DROP CONSTRAINT PK_deelnemer;
ALTER TABLE event DROP CONSTRAINT PK_event;
ALTER TABLE hok DROP CONSTRAINT PK_hok;
ALTER TABLE inschrijving_header DROP CONSTRAINT PK_INSCHRIJVING_HEADER;
ALTER TABLE inschrijving_lijn DROP CONSTRAINT PK_INSCHRIJVING_LIJN;
ALTER TABLE kleur DROP CONSTRAINT PK_KLEURTEMP;
ALTER TABLE ras DROP CONSTRAINT PK_RAS;
ALTER TABLE ras_kleur DROP CONSTRAINT PK_RAS_KLEUR;
ALTER TABLE soort DROP CONSTRAINT PK_SOORT;
ALTER TABLE vereniging DROP CONSTRAINT PK_VERENIGING;

CREATE TABLE aantal_2 (
    id int NOT NULL generated by default as identity ( start with 20, increment by 1 ),
    naam     VARCHAR(5)             not null,
    aantal   INTEGER                not null,
    aantal2  SMALLINT,
    benaming VARCHAR(20) default '' not null,
    constraint PK_AANTAL primary key (id)
);
INSERT INTO aantal_2 SELECT * FROM aantal e ORDER BY e.id;
DROP TABLE aantal;
RENAME TABLE aantal_2 TO aantal;

CREATE TABLE deelnemer_2 (
    id int NOT NULL generated by default as identity ( start with 500, increment by 1 ),
    NAAM                VARCHAR(50) not null,
    STRAAT              VARCHAR(100),
    WOONPLAATS          VARCHAR(100),
    TELEFOON            VARCHAR(50),
    VERENIGING_ID       INTEGER,
    FOKKERSKAART_NUMMER VARCHAR(20),
    JEUGDDEELNEMER      NUMERIC(4),
    constraint PK_DEELNEMER primary key (id)
);
INSERT INTO deelnemer_2 SELECT * FROM deelnemer e ORDER BY e.id;
DROP TABLE deelnemer;
RENAME TABLE deelnemer_2 TO deelnemer;

CREATE TABLE event_2 (
    id int NOT NULL generated by default as identity ( start with 50, increment by 1 ),
    type varchar(50) NOT NULL,
    naam varchar(100),
    dieren numeric(6, 2) NOT NULL,
    dieren_club numeric(6, 2) NOT NULL,
    dieren_te_koop numeric(6, 2) NOT NULL,
    palmares numeric(6, 2) NOT NULL,
    lidgeld numeric(6, 2) NOT NULL,
    lidgeld_jeugd numeric(6, 2) NOT NULL,
    fokkerskaart numeric(6, 2) NOT NULL,
    fokkerskaart_2 numeric(6, 2) NOT NULL,
    selected varchar(5) NOT NULL DEFAULT 'False',
    club_naam_regel_1 VARCHAR(20)  NOT NULL  DEFAULT 'Kleindierclub',
    club_naam_regel_2 VARCHAR(20)  NOT NULL  DEFAULT 'AVIVARIA VZW.',
    CONSTRAINT PK_event PRIMARY KEY ( id )
);
INSERT INTO event_2 SELECT * FROM event e ORDER BY e.id;
DROP TABLE event;
RENAME TABLE event_2 TO event;

CREATE TABLE hok_2 (
    id int NOT NULL generated by default as identity ( start with 20000, increment by 1 ),
    INSCHRIJVING_LIJN_ID INTEGER           not null,
    HOKNUMMER            INTEGER,
    AANTAL_ID            INTEGER,
    PRIJS                VARCHAR(50),
    OPMERKING            VARCHAR(50),
    TYPE                 INTEGER default 0 not null,
    PREDICAAT            VARCHAR(8),
    constraint PK_HOK primary key (id)
);
INSERT INTO hok_2 SELECT * FROM hok e ORDER BY e.id;
DROP TABLE hok;
RENAME TABLE hok_2 TO hok;

CREATE TABLE inschrijving_header_2 (
    id int NOT NULL generated by default as identity ( start with 1300, increment by 1 ),
    EVENT_ID      INTEGER                    not null,
    VOLGNUMMER    INTEGER,
    DEELNEMER_ID  INTEGER                    not null,
    PALMARES      VARCHAR(5) default 'False' not null,
    FOKKERSKAART  VARCHAR(5) default 'False' not null,
    FOKKERSKAART2 VARCHAR(5) default 'False' not null,
    LIDGELD       VARCHAR(5) default 'False' not null,
    LIDGELD2      VARCHAR(5) default 'False' not null,
    LID_AVIVARIA  VARCHAR(5) default 'False' not null,
    constraint PK_INSCHRIJVING_HEADER primary key (id)
);
INSERT INTO inschrijving_header_2 SELECT * FROM inschrijving_header e ORDER BY e.id;
DROP TABLE inschrijving_header;
RENAME TABLE inschrijving_header_2 TO inschrijving_header;

CREATE TABLE inschrijving_lijn_2 (
    id int NOT NULL generated by default as identity ( start with 10000, increment by 1 ),
    INSCHRIJVING_HEADER_ID INTEGER not null,
    RAS_ID                 INTEGER not null,
    KLEUR_ID               INTEGER not null,
    LEEFTIJD               VARCHAR(5),
    AANTAL_ID              INTEGER,
    RINGNUMMER             VARCHAR(50),
    PRIJS                  DECIMAL(6, 2),
    constraint PK_INSCHRIJVING_LIJN primary key (id)
);
INSERT INTO inschrijving_lijn_2 SELECT * FROM inschrijving_lijn e ORDER BY e.id;
DROP TABLE inschrijving_lijn;
RENAME TABLE inschrijving_lijn_2 TO inschrijving_lijn;

CREATE TABLE kleur_2 (
    id int NOT NULL generated by default as identity ( start with 1000, increment by 1 ),
    NAAM VARCHAR(50),
    constraint PK_KLEUR primary key (id)
);
INSERT INTO kleur_2 SELECT * FROM kleur e ORDER BY e.id;
DROP TABLE kleur;
RENAME TABLE kleur_2 TO kleur;

CREATE TABLE ras_2 (
    id int NOT NULL generated by default as identity ( start with 1100, increment by 1 ),
    SOORT_ID      INTEGER                    not null,
    NAAM          VARCHAR(100)               not null,
    ERKEND        VARCHAR(5)                 not null,
    HOKTYPE_MAN   INTEGER    default 0       not null,
    HOKTYPE_VROUW INTEGER    default 0       not null,
    BELGISCH      VARCHAR(5) default 'False' not null,
    VOLGORDE      INTEGER    default 1000    not null,
    constraint PK_RAS primary key (id)
);
INSERT INTO ras_2 SELECT * FROM ras e ORDER BY e.id;
DROP TABLE ras;
RENAME TABLE ras_2 TO ras;

CREATE TABLE ras_kleur_2 (
    id int NOT NULL generated by default as identity ( start with 5000, increment by 1 ),
    RAS_ID   INTEGER    not null,
    KLEUR_ID INTEGER    not null,
    ERKEND   VARCHAR(5) not null,
    constraint PK_RAS_KLEUR primary key (id)
);
INSERT INTO ras_kleur_2 SELECT * FROM ras_kleur e ORDER BY e.id;
DROP TABLE ras_kleur;
RENAME TABLE ras_kleur_2 TO ras_kleur;

CREATE TABLE soort_2 (
    id int NOT NULL generated by default as identity ( start with 150, increment by 1 ),
    AFKORTING VARCHAR(2)  not null,
    NAAM      VARCHAR(50) not null,
    constraint PK_SOORT primary key (id)
);
INSERT INTO soort_2 SELECT * FROM soort e ORDER BY e.id;
DROP TABLE soort;
RENAME TABLE soort_2 TO soort;

CREATE TABLE vereniging_2 (
    id int NOT NULL generated by default as identity ( start with 50, increment by 1 ),
    NAAM VARCHAR(100) not null,
    constraint PK_VERENIGING primary key (id)
);
INSERT INTO vereniging_2 SELECT * FROM vereniging e ORDER BY e.id;
DROP TABLE vereniging;
RENAME TABLE vereniging_2 TO vereniging;

ALTER TABLE deelnemer ADD CONSTRAINT FK_DEELNEMER_VERENIGING FOREIGN KEY(vereniging_id) REFERENCES vereniging (id);
ALTER TABLE hok ADD CONSTRAINT FK_HOK_AANTAL FOREIGN KEY(aantal_id) REFERENCES aantal (id);
ALTER TABLE hok ADD CONSTRAINT FK_HOK_INSCHRIJVING_LIJN FOREIGN KEY(inschrijving_lijn_id) REFERENCES inschrijving_lijn (id);
ALTER TABLE inschrijving_header ADD CONSTRAINT FK_INSCHRIJVING_HEADER_DEELNEMER FOREIGN KEY(deelnemer_id) REFERENCES deelnemer (id);
ALTER TABLE inschrijving_header ADD CONSTRAINT FK_inschrijving_header_event FOREIGN KEY(event_id) REFERENCES event (id);
ALTER TABLE inschrijving_lijn ADD CONSTRAINT FK_INSCHRIJVING_LIJN_AANTAL FOREIGN KEY(aantal_id) REFERENCES aantal (id);
ALTER TABLE inschrijving_lijn ADD CONSTRAINT FK_INSCHRIJVING_LIJN_INSCHRIJVING_HEADER FOREIGN KEY(inschrijving_header_id) REFERENCES inschrijving_header (id);
ALTER TABLE inschrijving_lijn ADD CONSTRAINT FK_INSCHRIJVING_LIJN_KLEUR FOREIGN KEY(kleur_id) REFERENCES kleur (id);
ALTER TABLE inschrijving_lijn ADD CONSTRAINT FK_INSCHRIJVING_LIJN_RAS FOREIGN KEY(ras_id) REFERENCES ras (id);
ALTER TABLE ras ADD CONSTRAINT FK_RAS_SOORT FOREIGN KEY(soort_id) REFERENCES soort (id);
ALTER TABLE ras_kleur ADD CONSTRAINT FK_RAS_KLEUR_KLEUR FOREIGN KEY(kleur_id) REFERENCES kleur (id);
ALTER TABLE ras_kleur ADD CONSTRAINT FK_RAS_KLEUR_RAS FOREIGN KEY(ras_id) REFERENCES ras (id);

UPDATE VERSION SET VERSION = '3.0';
