ALTER TABLE event ADD COLUMN hok_start_nummer INTEGER  NOT NULL  DEFAULT 1;

CREATE TABLE keurmeester (
  id int NOT NULL generated by default as identity ( start with 1, increment by 1 ),
  event_id          INTEGER                not null,
  ras_id            INTEGER                not null,
  kleur_id          INTEGER                        ,
  naam              VARCHAR(50)            not null,
  constraint PK_KEURMEESTER primary key (id)
);

ALTER TABLE keurmeester ADD CONSTRAINT FK_keurmeester_event FOREIGN KEY(event_id) REFERENCES event (id);
ALTER TABLE keurmeester ADD CONSTRAINT FK_keurmeester_ras FOREIGN KEY(ras_id) REFERENCES ras (id);
ALTER TABLE keurmeester ADD CONSTRAINT FK_keurmeester_kleur FOREIGN KEY(kleur_id) REFERENCES kleur (id);

UPDATE VERSION SET VERSION = '3.1';
